package hibernate;
// Generated 08-Aug-2017 14:17:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DemoProductInfo generated by hbm2java
 */
@Entity
@Table(name="DEMO_PRODUCT_INFO"
    ,schema="MONIR"
)
public class DemoProductInfo  implements java.io.Serializable {


     private BigDecimal productId;
     private String productName;
     private String productDescription;
     private String category;
     private String productAvail;
     private BigDecimal listPrice;
     private Blob productImage;
     private String mimetype;
     private String filename;
     private Date imageLastUpdate;
     private Set demoOrderItemses = new HashSet(0);

    public DemoProductInfo() {
    }

	
    public DemoProductInfo(BigDecimal productId) {
        this.productId = productId;
    }
    public DemoProductInfo(BigDecimal productId, String productName, String productDescription, String category, String productAvail, BigDecimal listPrice, Blob productImage, String mimetype, String filename, Date imageLastUpdate, Set demoOrderItemses) {
       this.productId = productId;
       this.productName = productName;
       this.productDescription = productDescription;
       this.category = category;
       this.productAvail = productAvail;
       this.listPrice = listPrice;
       this.productImage = productImage;
       this.mimetype = mimetype;
       this.filename = filename;
       this.imageLastUpdate = imageLastUpdate;
       this.demoOrderItemses = demoOrderItemses;
    }
   
     @Id 

    
    @Column(name="PRODUCT_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getProductId() {
        return this.productId;
    }
    
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    
    @Column(name="PRODUCT_NAME", length=50)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="PRODUCT_DESCRIPTION", length=2000)
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    
    @Column(name="CATEGORY", length=30)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="PRODUCT_AVAIL", length=1)
    public String getProductAvail() {
        return this.productAvail;
    }
    
    public void setProductAvail(String productAvail) {
        this.productAvail = productAvail;
    }

    
    @Column(name="LIST_PRICE", precision=8)
    public BigDecimal getListPrice() {
        return this.listPrice;
    }
    
    public void setListPrice(BigDecimal listPrice) {
        this.listPrice = listPrice;
    }

    
    @Column(name="PRODUCT_IMAGE")
    public Blob getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(Blob productImage) {
        this.productImage = productImage;
    }

    
    @Column(name="MIMETYPE")
    public String getMimetype() {
        return this.mimetype;
    }
    
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    
    @Column(name="FILENAME", length=400)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="IMAGE_LAST_UPDATE", length=7)
    public Date getImageLastUpdate() {
        return this.imageLastUpdate;
    }
    
    public void setImageLastUpdate(Date imageLastUpdate) {
        this.imageLastUpdate = imageLastUpdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="demoProductInfo")
    public Set getDemoOrderItemses() {
        return this.demoOrderItemses;
    }
    
    public void setDemoOrderItemses(Set demoOrderItemses) {
        this.demoOrderItemses = demoOrderItemses;
    }




}


