package hibernate;
// Generated 08-Aug-2017 14:17:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DemoCustomers generated by hbm2java
 */
@Entity
@Table(name="DEMO_CUSTOMERS"
    ,schema="MONIR"
)
public class DemoCustomers  implements java.io.Serializable {


     private BigDecimal customerId;
     private String custFirstName;
     private String custLastName;
     private String custStreetAddress1;
     private String custStreetAddress2;
     private String custCity;
     private String custState;
     private String custPostalCode;
     private String phoneNumber1;
     private String phoneNumber2;
     private BigDecimal creditLimit;
     private String custEmail;
     private Set demoOrderses = new HashSet(0);

    public DemoCustomers() {
    }

	
    public DemoCustomers(BigDecimal customerId, String custFirstName, String custLastName) {
        this.customerId = customerId;
        this.custFirstName = custFirstName;
        this.custLastName = custLastName;
    }
    public DemoCustomers(BigDecimal customerId, String custFirstName, String custLastName, String custStreetAddress1, String custStreetAddress2, String custCity, String custState, String custPostalCode, String phoneNumber1, String phoneNumber2, BigDecimal creditLimit, String custEmail, Set demoOrderses) {
       this.customerId = customerId;
       this.custFirstName = custFirstName;
       this.custLastName = custLastName;
       this.custStreetAddress1 = custStreetAddress1;
       this.custStreetAddress2 = custStreetAddress2;
       this.custCity = custCity;
       this.custState = custState;
       this.custPostalCode = custPostalCode;
       this.phoneNumber1 = phoneNumber1;
       this.phoneNumber2 = phoneNumber2;
       this.creditLimit = creditLimit;
       this.custEmail = custEmail;
       this.demoOrderses = demoOrderses;
    }
   
     @Id 

    
    @Column(name="CUSTOMER_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(BigDecimal customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="CUST_FIRST_NAME", nullable=false, length=20)
    public String getCustFirstName() {
        return this.custFirstName;
    }
    
    public void setCustFirstName(String custFirstName) {
        this.custFirstName = custFirstName;
    }

    
    @Column(name="CUST_LAST_NAME", nullable=false, length=20)
    public String getCustLastName() {
        return this.custLastName;
    }
    
    public void setCustLastName(String custLastName) {
        this.custLastName = custLastName;
    }

    
    @Column(name="CUST_STREET_ADDRESS1", length=60)
    public String getCustStreetAddress1() {
        return this.custStreetAddress1;
    }
    
    public void setCustStreetAddress1(String custStreetAddress1) {
        this.custStreetAddress1 = custStreetAddress1;
    }

    
    @Column(name="CUST_STREET_ADDRESS2", length=60)
    public String getCustStreetAddress2() {
        return this.custStreetAddress2;
    }
    
    public void setCustStreetAddress2(String custStreetAddress2) {
        this.custStreetAddress2 = custStreetAddress2;
    }

    
    @Column(name="CUST_CITY", length=30)
    public String getCustCity() {
        return this.custCity;
    }
    
    public void setCustCity(String custCity) {
        this.custCity = custCity;
    }

    
    @Column(name="CUST_STATE", length=2)
    public String getCustState() {
        return this.custState;
    }
    
    public void setCustState(String custState) {
        this.custState = custState;
    }

    
    @Column(name="CUST_POSTAL_CODE", length=10)
    public String getCustPostalCode() {
        return this.custPostalCode;
    }
    
    public void setCustPostalCode(String custPostalCode) {
        this.custPostalCode = custPostalCode;
    }

    
    @Column(name="PHONE_NUMBER1", length=25)
    public String getPhoneNumber1() {
        return this.phoneNumber1;
    }
    
    public void setPhoneNumber1(String phoneNumber1) {
        this.phoneNumber1 = phoneNumber1;
    }

    
    @Column(name="PHONE_NUMBER2", length=25)
    public String getPhoneNumber2() {
        return this.phoneNumber2;
    }
    
    public void setPhoneNumber2(String phoneNumber2) {
        this.phoneNumber2 = phoneNumber2;
    }

    
    @Column(name="CREDIT_LIMIT", precision=9)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="CUST_EMAIL", length=30)
    public String getCustEmail() {
        return this.custEmail;
    }
    
    public void setCustEmail(String custEmail) {
        this.custEmail = custEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="demoCustomers")
    public Set getDemoOrderses() {
        return this.demoOrderses;
    }
    
    public void setDemoOrderses(Set demoOrderses) {
        this.demoOrderses = demoOrderses;
    }




}


