package hibernate;
// Generated 08-Aug-2017 14:17:43 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DemoStates generated by hbm2java
 */
@Entity
@Table(name="DEMO_STATES"
    ,schema="MONIR"
)
public class DemoStates  implements java.io.Serializable {


     private DemoStatesId id;

    public DemoStates() {
    }

    public DemoStates(DemoStatesId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="st", column=@Column(name="ST", length=30) ), 
        @AttributeOverride(name="stateName", column=@Column(name="STATE_NAME", length=30) ) } )
    public DemoStatesId getId() {
        return this.id;
    }
    
    public void setId(DemoStatesId id) {
        this.id = id;
    }




}


