package hibernate;
// Generated 08-Aug-2017 14:17:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemoStatesId generated by hbm2java
 */
@Embeddable
public class DemoStatesId  implements java.io.Serializable {


     private String st;
     private String stateName;

    public DemoStatesId() {
    }

    public DemoStatesId(String st, String stateName) {
       this.st = st;
       this.stateName = stateName;
    }
   


    @Column(name="ST", length=30)
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }


    @Column(name="STATE_NAME", length=30)
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DemoStatesId) ) return false;
		 DemoStatesId castOther = ( DemoStatesId ) other; 
         
		 return ( (this.getSt()==castOther.getSt()) || ( this.getSt()!=null && castOther.getSt()!=null && this.getSt().equals(castOther.getSt()) ) )
 && ( (this.getStateName()==castOther.getStateName()) || ( this.getStateName()!=null && castOther.getStateName()!=null && this.getStateName().equals(castOther.getStateName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSt() == null ? 0 : this.getSt().hashCode() );
         result = 37 * result + ( getStateName() == null ? 0 : this.getStateName().hashCode() );
         return result;
   }   


}


