package hibernate;
// Generated 08-Aug-2017 14:17:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NotificationHistory generated by hbm2java
 */
@Entity
@Table(name="NOTIFICATION_HISTORY"
    ,schema="MONIR"
)
public class NotificationHistory  implements java.io.Serializable {


     private BigDecimal id;
     private String stationName;
     private String viewNo;

    public NotificationHistory() {
    }

	
    public NotificationHistory(BigDecimal id) {
        this.id = id;
    }
    public NotificationHistory(BigDecimal id, String stationName, String viewNo) {
       this.id = id;
       this.stationName = stationName;
       this.viewNo = viewNo;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=20, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="STATION_NAME", length=100)
    public String getStationName() {
        return this.stationName;
    }
    
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    
    @Column(name="VIEW_NO", length=50)
    public String getViewNo() {
        return this.viewNo;
    }
    
    public void setViewNo(String viewNo) {
        this.viewNo = viewNo;
    }




}


