package hibernate;
// Generated 23-Jul-2017 01:43:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Test1 generated by hbm2java
 */
@Entity
@Table(name="TEST1"
    ,schema="MONIR"
)
public class Test1  implements java.io.Serializable {


     private long id;
     private String email;
     private String name;
     private String password;

    public Test1() {
    }

    public Test1(String email, String name, String password) {
       this.email = email;
       this.name = name;
       this.password = password;
    }
   
     @GenericGenerator(name="generator", strategy="seqhilo", parameters={@Parameter(name="max_lo", value="49"), @Parameter(name="sequence", value="TEST1_SEQ")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


